import os
from fpdf import FPDF

# Color Palette
DARK_BLUE = (26, 37, 48)
TEAL = (0, 180, 216)
LIGHT_GRAY = (244, 246, 247)
WHITE = (255, 255, 255)
TEXT_DARK = (40, 40, 40)
TEXT_LIGHT = (100, 100, 100)

class DesignerPDF(FPDF):
    def __init__(self):
        super().__init__()
        # Add custom designer fonts
        self.add_font("Roboto", "", "Roboto-Regular.ttf")
        self.add_font("Roboto", "B", "Roboto-Bold.ttf")
        self.add_font("Roboto", "I", "Roboto-Italic.ttf")
        self.set_auto_page_break(auto=True, margin=20)
        self.custom_title = ""

    def header(self):
        # Draw a beautiful top geometric header
        self.set_fill_color(*DARK_BLUE)
        self.rect(0, 0, 210, 35, "F")
        self.set_fill_color(*TEAL)
        self.rect(0, 33, 210, 2, "F") # Accent line
        
        self.set_y(15)
        self.set_font("Roboto", "B", 24)
        self.set_text_color(*WHITE)
        self.cell(0, 0, "TORTUGA CYBERSECURITY", align="C")
        self.ln(12)

    def footer(self):
        self.set_y(-20)
        self.set_fill_color(*TEAL)
        self.rect(0, 287, 210, 10, "F") # Bottom accent
        self.set_font("Roboto", "", 9)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by TORTUGA Security", align="C")

    def chapter_title(self, title):
        self.ln(10)
        # Background block for title
        self.set_fill_color(*LIGHT_GRAY)
        self.rect(10, self.get_y(), 190, 12, "F")
        self.set_fill_color(*TEAL)
        self.rect(10, self.get_y(), 3, 12, "F") # Left accent line
        
        self.set_y(self.get_y() + 3)
        self.set_x(18)
        self.set_font("Roboto", "B", 14)
        self.set_text_color(*DARK_BLUE)
        self.cell(0, 6, title)
        self.ln(6)

    def chapter_body(self, body):
        self.set_font("Roboto", "", 11)
        self.set_text_color(*TEXT_DARK)
        
        # We replace some markdown-like syntax for bolding
        # We will just write HTML for the body to make bolding easier
        # But fpdf2 write_html with custom fonts needs the font to be registered.
        self.write_html(body)
        self.ln(5)

def get_en_content():
    return [
        {
            "title": "What is Phishing?",
            "body": "<p><b>Phishing</b> is a social engineering attack where cybercriminals send deceptive emails or messages designed to trick you into revealing sensitive information. They often masquerade as trusted entities (like your bank, government agencies, or popular services like Netflix) to steal passwords, financial details, or personal data.</p>"
        },
        {
            "title": "How to Spot a Phishing Attack",
            "body": """
            <ul>
                <li><b>Urgent or Threatening Language:</b> Phrases like <i>"Your account will be suspended immediately"</i> are designed to trigger panic.</li>
                <li><b>Generic Greetings:</b> Using <i>"Dear Customer"</i> instead of your actual name.</li>
                <li><b>Mismatched Sender Addresses:</b> The email displays "PayPal Support", but the actual address is <i>security@paypal-update123.com</i>.</li>
                <li><b>Suspicious Links (Homograph Attacks):</b> Links that look legitimate but contain slight typos (e.g., <i>amazon.com</i> vs <i>arnazon.com</i>). Always hover over links before clicking.</li>
            </ul>
            """
        },
        {
            "title": "The Golden Rules of Protection",
            "body": """
            <ul>
                <li><b>Never click links in unexpected emails.</b> Navigate to the website manually by typing the URL in your browser.</li>
                <li><b>Enable Multi-Factor Authentication (MFA).</b> Even if a hacker steals your password, they cannot access your account without the second factor (like an authenticator app code).</li>
                <li><b>Use a Password Manager.</b> They generate impossible-to-guess passwords and will refuse to auto-fill your credentials on a fake phishing website.</li>
            </ul>
            """
        },
        {
            "title": "Public Wi-Fi & Network Security",
            "body": "<p>When connecting to public Wi-Fi (coffee shops, airports), your data can be intercepted by anyone on the same network. <b>Never access banking or sensitive accounts on public Wi-Fi</b> unless you are using a trusted VPN (Virtual Private Network). A VPN encrypts your traffic, creating a secure tunnel that hackers cannot see into.</p>"
        },
        {
            "title": "Ransomware & Malware",
            "body": "<p><b>Ransomware</b> encrypts all your personal files and demands payment for the decryption key. <b>Malware</b> operates silently to steal your data or resources. <br><br><b>Defense Strategy:</b> Keep your Operating System and apps updated. Updates contain critical security patches. Most importantly, maintain regular, offline backups of your most important files using an external hard drive. If you get infected, you can wipe your computer and restore your files for free.</p>"
        },
        {
            "title": "Social Engineering: The Human Element",
            "body": "<p>Hackers know that breaking into a computer is hard, but tricking a human is easy. Be skeptical of unsolicited phone calls claiming to be from 'Microsoft Tech Support' or your bank asking for verification codes. A legitimate company will <b>never</b> ask for your password or a 2FA code over the phone.</p>"
        }
    ]

def get_es_content():
    return [
        {
            "title": "¿Qué es el Phishing?",
            "body": "<p>El <b>Phishing</b> es un ataque de ingeniería social donde los cibercriminales envían correos o mensajes engañosos diseñados para que reveles información confidencial. A menudo se hacen pasar por entidades de confianza (como tu banco, agencias gubernamentales o servicios como Netflix) para robar contraseñas o datos financieros.</p>"
        },
        {
            "title": "Cómo Detectar un Ataque de Phishing",
            "body": """
            <ul>
                <li><b>Lenguaje Urgente o Amenazante:</b> Frases como <i>"Su cuenta será suspendida de inmediato"</i> están diseñadas para generar pánico.</li>
                <li><b>Saludos Genéricos:</b> Usar <i>"Estimado Cliente"</i> en lugar de tu nombre real.</li>
                <li><b>Remitentes Sospechosos:</b> El correo dice "Soporte de PayPal", pero la dirección real es <i>seguridad@paypal-update123.com</i>.</li>
                <li><b>Enlaces Falsos (Ataques Homógrafos):</b> Enlaces que parecen legítimos pero contienen pequeños errores tipográficos (ej. <i>amazon.com</i> vs <i>arnazon.com</i>). Siempre pasa el ratón sobre los enlaces antes de hacer clic.</li>
            </ul>
            """
        },
        {
            "title": "Las Reglas de Oro para Protegerte",
            "body": """
            <ul>
                <li><b>Nunca hagas clic en enlaces de correos inesperados.</b> Ve al sitio web escribiendo manualmente la dirección en tu navegador.</li>
                <li><b>Activa la Autenticación de Dos Pasos (2FA).</b> Incluso si un hacker roba tu contraseña, no podrá acceder a tu cuenta sin el segundo factor (como un código de una app autenticadora).</li>
                <li><b>Usa un Gestor de Contraseñas.</b> Generan contraseñas imposibles de adivinar y se negarán a autocompletar tus datos en una página web falsa de phishing.</li>
            </ul>
            """
        },
        {
            "title": "Wi-Fi Público y Seguridad de Red",
            "body": "<p>Al conectarte a Wi-Fi público (cafeterías, aeropuertos), tus datos pueden ser interceptados por cualquiera en la misma red. <b>Nunca accedas a cuentas bancarias en Wi-Fi público</b> a menos que uses una VPN (Red Privada Virtual) de confianza. Una VPN encripta tu tráfico, creando un túnel seguro que los hackers no pueden ver.</p>"
        },
        {
            "title": "Ransomware y Malware",
            "body": "<p>El <b>Ransomware</b> secuestra y encripta todos tus archivos personales y exige un pago para liberarlos. El <b>Malware</b> opera en silencio para robar tus datos. <br><br><b>Estrategia de Defensa:</b> Mantén tu Sistema Operativo y aplicaciones actualizados. Lo más importante: mantén copias de seguridad regulares y desconectadas de tus archivos más importantes usando un disco duro externo. Si te infectas, puedes borrar tu computadora y restaurar tus archivos gratis.</p>"
        },
        {
            "title": "Ingeniería Social: El Factor Humano",
            "body": "<p>Los hackers saben que hackear una computadora es difícil, pero engañar a un humano es fácil. Sé escéptico ante llamadas telefónicas no solicitadas que afirman ser del 'Soporte Técnico de Microsoft' o de tu banco pidiendo códigos de verificación. Una empresa legítima <b>nunca</b> te pedirá tu contraseña o un código 2FA por teléfono.</p>"
        }
    ]

def create_pdf(filename, title, content_sections):
    pdf = DesignerPDF()
    pdf.add_page()
    
    # Main Title Header (Below the geometric band)
    pdf.set_y(45)
    pdf.set_font("Roboto", "B", 20)
    pdf.set_text_color(*DARK_BLUE)
    pdf.cell(0, 10, title, align="C")
    pdf.ln()
    
    pdf.set_font("Roboto", "", 12)
    pdf.set_text_color(*TEXT_LIGHT)
    subtitle = "A Guide to Protecting Yourself Online" if "Phishing" in title and "Guide" in title else "Una Guía para Protegerte en Línea"
    pdf.cell(0, 6, subtitle, align="C")
    pdf.ln()
    pdf.ln(5)

    for section in content_sections:
        pdf.chapter_title(section["title"])
        # Replace newlines in body to avoid weird HTML parsing issues, ensure it's a tight string
        body = section["body"].replace('\n', ' ')
        
        # Apply specific CSS via write_html if possible, or just raw HTML
        # fpdf2 allows some styling
        pdf.chapter_body(body)
        
    os.makedirs("docs", exist_ok=True)
    pdf.output(filename)

if __name__ == "__main__":
    create_pdf("docs/PHISHING_AND_ATTACKS_EN.pdf", "Phishing & Common Cyber Attacks", get_en_content())
    create_pdf("docs/PHISHING_Y_ATAQUES_ES.pdf", "Phishing y Ataques Cibernéticos", get_es_content())
    print("Designer PDFs generated successfully.")
